node {
   stage('checkout'){
       
    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '4a5ccc92-d851-448c-ac3c-1761557bdbd1', url: 'https://github.com/mounirmahmoud/spring-cloud.git']]])
    def workspace  
   }
   stage('Static code analytics'){
      echo "Static code analytics" 
   }
   stage('build coe'){
     echo "Build code"  
   }
   
   stage('unit testing'){
     echo "Unit Testing"  
   }
}
