INSERT INTO QUOTE(DESCRIPTION) VALUES ('Quote 1');
INSERT INTO QUOTE(DESCRIPTION) VALUES ('Quote 2');
INSERT INTO QUOTE(DESCRIPTION) VALUES ('Quote 3');
INSERT INTO QUOTE(DESCRIPTION) VALUES ('Quote 4');
INSERT INTO QUOTE(DESCRIPTION) VALUES ('Quote 5');
INSERT INTO QUOTE(DESCRIPTION) VALUES ('Quote 6');